.PHONY: front, back

README.md: README.Rmd src/app/*.json src/app/*.js
	R -e 'rmarkdown::render("README.Rmd")'
	rm README.html

tiles:
	# Depends on links.geojson being generated by pack, but can't be bothered to set up proper makefile dependencies yet
	./src/data-preparation/tiles.sh data/sensitive/GCVT_Scenario_Pack/processed/links.geojson data/sensitive/GCVT_Scenario_Pack/processed/tiles
	./src/data-preparation/tiles.sh data/sensitive/GCVT_Scenario_Pack/geometry/zones.geojson data/sensitive/GCVT_Scenario_Pack/processed/tiles

pack:
	Rscript ./src/data-preparation/process_pack_dir.R

process_pack_dir:
	Rscript src/data-preparation/process_pack_dir.R

front:
	cd src/app/ && yarn build

back:
	./caddy&
	R -e 'shiny::runApp("src/app", port=6619)'
