# adapted from https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
version: '3.7'

services:
  traefik: # proxy
    container_name: traefik
    image: traefik:v1.7-alpine
    command: --docker --docker.domain=traefik --loglevel=INFO
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=traefik_proxy"
    networks: 
      - traefik_proxy

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks: 
      - database

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306 # mysql's default port
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - database
      - frontends

  julia:
    container_name: julia
    restart: unless-stopped
    build:
      context: backend/
      dockerfile: backend/Dockerfile
    labels:
      - "traefik.frontend.priority=3" # Need more priority than nginx
      - "traefik.frontend.rule=PathPrefix: /api/;"
      - "traefik.backend=oembed"
      - "traefik.docker.network=traefik_proxy"
      - traefik.port=8000
    networks: 
      - traefik_proxy

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    labels:
    - traefik.port=8080
    - "traefik.frontend.priority=1"
    - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
    - "traefik.backend=webserver"
    - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - frontends

volumes:
  wordpress:
  dbdata:

networks:
  traefik_proxy:
    name: traefik_proxy
  database:
    name: database
  frontends:
    name: frontends
