library(shiny)

projects = c("Demo project", "2018-02-07 14:02 TEST", "2018-02-07 14:03 TEST 2")

ui = fluidPage(
  titlePanel("Project settings"),

  sidebarLayout(
    sidebarPanel(
        h3("Projects"),

        # Get a list of projects
        div(id="projectList",
            tags$ul(class="list-group",
                    lapply(projects, function(project) {
                      tags$li(class="list-group-item", a(href="#", class="projectItem", project))
                    })
              )
            ),
        actionButton("newProj", "New Project")
      ),
    mainPanel(
      # The below can probably be generated by a helper function when a project is clicked
        h2("Project setup"),
        # Get a list of project assets:
        # Link based
        h3("Network Link files"),
        p(id="linksFiles", "Load | Check | Remove"),
        h3("Origin-Destination Zone files"),
        p(id="odFiles", "Load | Check | Remove"),
        h3("Other project options"),
        p(checkboxInput("lockProject", "Lock project"),
          checkboxInput("publicProject", "Publicly viewable"))
      )
  )

)

server = function(input, output) {

  # Couldnt figure out how to listen for 'a' click - must be something simple
  observeEvent(input$projectItem, {
    print ("a project was clicked")
  })
}

# Run the application
shinyApp(ui = ui, server = server)
